### ISSUE TITLE
看到你在复现fpn的工作，请问你现在做的怎么样了？

### ISSUE THREAD

**Issue by unsky** [xmyqsh/RetinaNet#1]
可否加微信 cs2081264详聊，map可以达到论文的精度吗

**Comment by xmyqsh** [comment]
暂时没有
分析了下原因，发现按照论文描述的RetinaNet的结构，以及scale 600的输入图片大小，可能不太利于小物体的检测（相比于FPN），打算下一步把P7，P6反传给P5，增大P5, P4, P3能感受到的语义信息范围试试
